name: Update Readme on new public repo
on:
  repository_dispatch:
    types: [created]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Readme
        run: |
          echo "A new public repository has been created!" >> README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update README.md" -a
          git push
